### ISSUE TITLE
zipline.errors.InvalidCalendarName: The requested TradingCalendar, XNYS, does not exist.

### ISSUE THREAD

**Issue by ofmachin3s** [zipline-live/zipline#121]
Hi, I am trying to run the demo after installing zipline-live using python2.7 in a virtualenv but cannot get past this issue.

$ zipline run -f ~/zipline-algos/demo.py --state-file ~/zipline-algos/demo.state --realtime-bar-target ~/zipline-algos/realtime-bars/ --broker ib --broker-uri localhost:4002:1232 --bundle quantopian-quandl --data-frequency minute

> [2019-02-01 22:56:29.830541] INFO: IB Broker: Connecting: localhost:4002:1232
Server Version: 76
TWS Time at connection:20190201 17:56:29 EST
[2019-02-01 22:56:29.918050] INFO: IB Broker: [2104] Market data farm connection is OK:usfarm.nj (-1)
[2019-02-01 22:56:29.918326] INFO: IB Broker: [2104] Market data farm connection is OK:usfuture (-1)
[2019-02-01 22:56:29.918490] INFO: IB Broker: [2104] Market data farm connection is OK:usfarm (-1)
[2019-02-01 22:56:29.918640] INFO: IB Broker: [2106] HMDS data farm connection is OK:euhmds (-1)
[2019-02-01 22:56:29.918791] INFO: IB Broker: [2106] HMDS data farm connection is OK:fundfarm (-1)
[2019-02-01 22:56:29.918935] INFO: IB Broker: [2106] HMDS data farm connection is OK:ushmds (-1)
[2019-02-01 22:56:29.919022] DEBUG: IB Broker: Execution details completed for request 0
[2019-02-01 22:56:30.033363] INFO: IB Broker: Managed accounts: ['DUxxxxxx']
[2019-02-01 22:56:30.134061] INFO: IB Broker: Local-Broker Time Skew: 0 days 00:00:00
Traceback (most recent call last):
  File "/home/m/zipline/bin/zipline", line 10, in <module>
    sys.exit(main())
  File "/home/m/zipline/local/lib/python2.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/m/zipline/local/lib/python2.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/m/zipline/local/lib/python2.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/m/zipline/local/lib/python2.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/m/zipline/local/lib/python2.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/m/zipline/local/lib/python2.7/site-packages/zipline/__main__.py", line 102, in _
    return f(*args, **kwargs)
  File "/home/m/zipline/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/m/zipline/local/lib/python2.7/site-packages/zipline/__main__.py", line 316, in run
    realtime_bar_target=realtime_bar_target
  File "/home/m/zipline/local/lib/python2.7/site-packages/zipline/utils/run_algo.py", line 129, in _run
    bundle_timestamp,
  File "/home/m/zipline/local/lib/python2.7/site-packages/zipline/data/bundles/core.py", line 527, in load
    minute_equity_path(name, timestr, environ=environ),
  File "/home/m/zipline/local/lib/python2.7/site-packages/zipline/data/minute_bars.py", line 905, in __init__
    metadata = self._get_metadata()
  File "/home/m/zipline/local/lib/python2.7/site-packages/zipline/data/minute_bars.py", line 950, in _get_metadata
    return BcolzMinuteBarMetadata.read(self._rootdir)
  File "/home/m/zipline/local/lib/python2.7/site-packages/zipline/data/minute_bars.py", line 229, in read
    calendar = get_calendar(raw_data['calendar_name'])
  File "/home/m/zipline/local/lib/python2.7/site-packages/zipline/utils/calendars/calendar_utils.py", line 87, in get_calendar
    raise InvalidCalendarName(calendar_name=name)
zipline.errors.InvalidCalendarName: The requested TradingCalendar, XNYS, does not exist.

**Comment by HyperionSounds** [comment]
> Hi, I am trying to run the demo after installing zipline-live using python2.7 in a virtualenv but cannot get past this issue.
> 
> $ zipline run -f ~/zipline-algos/demo.py --state-file ~/zipline-algos/demo.state --realtime-bar-target ~/zipline-algos/realtime-bars/ --broker ib --broker-uri localhost:4002:1232 --bundle quantopian-quandl --data-frequency minute
> 
> > [2019-02-01 22:56:29.830541] INFO: IB Broker: Connecting: localhost:4002:1232
> > Server Version: 76
> > TWS Time at connection:20190201 17:56:29 EST
> > [2019-02-01 22:56:29.918050] INFO: IB Broker: [2104] Market data farm connection is OK:usfarm.nj (-1)
> > [2019-02-01 22:56:29.918326] INFO: IB Broker: [2104] Market data farm connection is OK:usfuture (-1)
> > [2019-02-01 22:56:29.918490] INFO: IB Broker: [2104] Market data farm connection is OK:usfarm (-1)
> > [2019-02-01 22:56:29.918640] INFO: IB Broker: [2106] HMDS data farm connection is OK:euhmds (-1)
> > [2019-02-01 22:56:29.918791] INFO: IB Broker: [2106] HMDS data farm connection is OK:fundfarm (-1)
> > [2019-02-01 22:56:29.918935] INFO: IB Broker: [2106] HMDS data farm connection is OK:ushmds (-1)
> > [2019-02-01 22:56:29.919022] DEBUG: IB Broker: Execution details completed for request 0
> > [2019-02-01 22:56:30.033363] INFO: IB Broker: Managed accounts: ['DUxxxxxx']
> > [2019-02-01 22:56:30.134061] INFO: IB Broker: Local-Broker Time Skew: 0 days 00:00:00
> > Traceback (most recent call last):
> > File "/home/m/zipline/bin/zipline", line 10, in 
> > sys.exit(main())
> > File "/home/m/zipline/local/lib/python2.7/site-packages/click/core.py", line 764, in **call**
> > return self.main(*args, **kwargs)
> > File "/home/m/zipline/local/lib/python2.7/site-packages/click/core.py", line 717, in main
> > rv = self.invoke(ctx)
> > File "/home/m/zipline/local/lib/python2.7/site-packages/click/core.py", line 1137, in invoke
> > return _process_result(sub_ctx.command.invoke(sub_ctx))
> > File "/home/m/zipline/local/lib/python2.7/site-packages/click/core.py", line 956, in invoke
> > return ctx.invoke(self.callback, **ctx.params)
> > File "/home/m/zipline/local/lib/python2.7/site-packages/click/core.py", line 555, in invoke
> > return callback(*args, **kwargs)
> > File "/home/m/zipline/local/lib/python2.7/site-packages/zipline/**main**.py", line 102, in _
> > return f(*args, **kwargs)
> > File "/home/m/zipline/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
> > return f(get_current_context(), *args, **kwargs)
> > File "/home/m/zipline/local/lib/python2.7/site-packages/zipline/**main**.py", line 316, in run
> > realtime_bar_target=realtime_bar_target
> > File "/home/m/zipline/local/lib/python2.7/site-packages/zipline/utils/run_algo.py", line 129, in _run
> > bundle_timestamp,
> > File "/home/m/zipline/local/lib/python2.7/site-packages/zipline/data/bundles/core.py", line 527, in load
> > minute_equity_path(name, timestr, environ=environ),
> > File "/home/m/zipline/local/lib/python2.7/site-packages/zipline/data/minute_bars.py", line 905, in **init**
> > metadata = self._get_metadata()
> > File "/home/m/zipline/local/lib/python2.7/site-packages/zipline/data/minute_bars.py", line 950, in _get_metadata
> > return BcolzMinuteBarMetadata.read(self._rootdir)
> > File "/home/m/zipline/local/lib/python2.7/site-packages/zipline/data/minute_bars.py", line 229, in read
> > calendar = get_calendar(raw_data['calendar_name'])
> > File "/home/m/zipline/local/lib/python2.7/site-packages/zipline/utils/calendars/calendar_utils.py", line 87, in get_calendar
> > raise InvalidCalendarName(calendar_name=name)
> > zipline.errors.InvalidCalendarName: The requested TradingCalendar, XNYS, does not exist.

XNYS Calendar - This error cropped up overnight. Something along the lines of 'not a valid trading calendar'... If you get the message: "zipline.errors.InvalidCalendarName: The requested TradingCalendar, XNYS, does not exist.", you may need to correct a calendar scheduling error (XNYS), in which case open up calendar_utils.py Go to your calendar_utils.py (venv->lib->python3.6->site-packages->zipline->utils->calendars->calendar_utils.py)

add XNYS to the default calendar aliases.

_default_calendar_aliases = {
   'SMART': 'NYSE',
   'ARCA': 'NYSE',
   'NASDAQ': 'NYSE',
   'XNYS': 'NYSE',
   'BATS': 'NYSE',
   'CBOT': 'CME',
   'COMEX': 'CME',
   'NYMEX': 'CME',
   'ICEUS': 'ICE',
   'NYFE': 'ICE',
}

**Comment by ofmachin3s** [comment]
I love you. Thank you.
